spring:
  application:
    name: goblin-api
  datasource:
      url: jdbc:h2:file:flashcards;DATABASE_TO_UPPER=false
      driverClassname: org.h2.Driver
      username: sa
      password: password
  jpa:
      hibernate:
        ddl-auto: update
      