spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: goblin-api
  datasource:
    url: jdbc:h2:mem:flashcards;DATABASE_TO_UPPER=false
    driverClassname: org.h2.Driver
    username: sa
    password: passwordq
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    url: /openapi.yaml
