spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: goblin-api
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: ${DATASOURCE_URL}
    driverClassname: ${DATASOURCE_DRIVER_CLASSNAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    url: /openapi/openapi.yaml
api:
  docs:
    uri: http://localhost:8080/swagger-ui/index.html
