spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: goblin-api
  datasource:
    url: jdbc:h2:mem:goblin;DATABASE_TO_UPPER=false
    driverClassname: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    url: /openapi/openapi.yaml
api:
  docs:
    uri: http://localhost:8080/swagger-ui/index.html
